name: Deploy special admin portal

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: "stone-and-ida-blog/"
      CLOUD_FRONT_DISTRIBUTION_ID: "E3B2GFHUF0BD0H"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        env:
          test: ${{ secrets.TEST }}
        run: |
          echo "${{ env.test }}" \
      - name: Configure AWS credentials for Special development environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: |
          yarn install
          echo "Ran yarn install"
          yarn build
          echo "Ran yarn build"
      - name: Remove files
        run: |
          aws s3 rm s3://${{env.S3_BUCKET_NAME}} --recursive --include '*' \
      - name: Add js files
        run: |
          aws s3 cp ./build/ s3://${{env.S3_BUCKET_NAME}} --recursive --exclude "*" --include "*.js" --content-type application/javascript --cache-control max-age=600 \
      - name: Add css files
        run: |
          aws s3 cp ./build/ s3://${{env.S3_BUCKET_NAME}} --recursive --exclude "*" --include "*.css" --content-type text/css --cache-control max-age=600 \
      - name: Add index.html
        run: |
          aws s3 cp ./build/ s3://${{env.S3_BUCKET_NAME}} --recursive --exclude "*" --include "*.html" --content-type text/html --cache-control max-age=600 \
      - name: Sync the rest
        run: |
          aws s3 sync --delete ./build/ s3://${{env.S3_BUCKET_NAME}} \
      - name: Invalidate cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_DISTRIBUTION_ID}} --paths "/*" \
